# Flutter / Android ProGuard rules for MovieGPT release builds.
#
# The Flutter engine ships its own consumer rules (referenced automatically).
# This file adds explicit keep rules for the reflection-based third-party
# libraries used by MovieGPT (Firebase, Google Sign-In, Dio) so the minified
# release build does NOT crash at runtime with NoSuchMethodError / missing
# classes. These keep rules are safe, additive, and standard across Android.

# --- Kotlin metadata (needed by several reflection-based libs) ---
-keep class kotlin.Metadata { *; }

# --- Firebase (Core, Auth, Firestore, Storage, Realtime DB) ---
# Firebase modules use reflection/annotations heavily; keep their model &
# internal class names to avoid release-only crashes.
-keep class com.google.firebase.** { *; }
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.firebase.**
-dontwarn com.google.android.gms.**

# --- Google Sign-In ---
-keep class com.google.android.gms.auth.api.signin.** { *; }
-keep class com.google.android.gms.common.** { *; }
-dontwarn com.google.android.gms.**

# --- Dio / OkHttp (networking) ---
# OkHttp uses reflection for some response-body adapters; keep its model classes.
-keep class okhttp3.** { *; }
-keep class okio.** { *; }
-keep class com.squareup.** { *; }
-dontwarn okhttp3.**
-dontwarn okio.**

# --- Gson (used by some Firebase/Google internals) ---
-keep class com.google.gson.** { *; }
-dontwarn com.google.gson.**

# --- Firebase model/entity classes generated by FCM/Remote Config ---
-keep class com.google.firebase.platforminfo.** { *; }
-keep class com.google.firebase.installations.** { *; }

# --- Keep the Flutter engine + app entry points (usually covered by Flutter's
#     own rules), included here defensively ---
-keep class io.flutter.embedding.** { *; }
-keep class io.flutter.plugin.** { *; }
-keep class io.flutter.app.** { *; }

# --- Keep the app's MainActivity and any classes referenced by name ---
-keep class com.piyushcode.moviegpt.MainActivity { *; }
